version: "3.3"

services:
  api:
    build: .
    ports:
      - "1234:1234"
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
      
networks:
  my-network:
